### PR TITLE
Temporarily pinning ember-data to specific known good SHA

### LINKED ISSUE #93: Blueprint fails with ember-data version error
Following the [Quickstart](https://octane-guides-preview.emberjs.com/release/getting-started/quick-start/), generating a new Octane app from the blueprint fails during the dependency installation step. The error indicates an invalid `ember-data` version.

Steps to reproduce:

1. `npm install -g ember-cli`
2. `ember new ember-quickstart -b @ember/octane-app-blueprint` or `ember new ember-quickstart -b @ember/octane-app-blueprint --yarn`

Results in the following error:

```
Error creating new application. Removing generated directory `./ember-quickstart`
Command failed: yarn install --non-interactive
error Can't add "ember-data": invalid package version undefined.

yarn install v1.15.2
info No lockfile found.
[1/5] Validating package.json...
[2/5] Resolving packages...
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.



Stack Trace and Error Report: /var/folders/3q/5x6gzths7b97lq08vx_cb0g4000gyd/T/error.dump.3d443c26e1cb6944c55d4bc317b013cd.log
```

The version of `ember-data` that's in the package.json is `"ember-data": "github:emberjs/data#1495b780952a1b1cb53060114490ba9554c1341d"`

Looking at [that commit in `emberjs/data`](https://github.com/emberjs/data/commit/1495b780952a1b1cb53060114490ba9554c1341d), it looks like CI is failing when doing compatibility testing with ember addons.

### PR DESCRIPTION
**Pull request by scalvert**
Fixes #93 

@NullVoxPopuli there wasn't any need to update the add blueprint, as it doesn't include `ember-data`.

### CODE REVIEW

File: packages/@ember/octane-app-blueprint/index.js [hunk 1]
```diff
@@ -22,6 +22,9 @@ module.exports = {
       let rawName = entity.name;
       let namespace = stringUtil.classify(rawName);
 
+      // temporarily pinning ember-data to specific known good SHA
```
Comment (rwjblue) [inline packages/@ember/octane-app-blueprint/index.js]:
```suggestion
      // temporarily pinning ember-data see tracking issue for details:
      // https://github.com/ember-cli/ember-octane-blueprint/issues/95 to
```
